### ISSUE TITLE
Blazor Client HotReload

### ISSUE THREAD

**Issue by roja** [dazinator/NetPack#51]
Hi,

I am attempting to make the NetPack.Web.Blazor sample work. I have grabbed the repo (master) and am running the project using the various configurations; IISExpress, NetPack.Web.Blazor and Watch but can get none of them to hot reload changes.

Could you give me a pointer int the right direction?

Thanks

**Comment by dazinator** [comment]
Please switch to develop branch and run it there and let me know if any issues.

**Comment by dazinator** [comment]
@roja any joy running the blazor example on the develop branch?

**Comment by dazinator** [comment]
Closing - aassuming its sorted, but let me know if not and I'll reopen.
